// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { GetApiAdminOrdersByIdData, GetApiAdminOrdersByIdErrors, GetApiAdminOrdersByIdResponses, GetApiAdminOrdersData, GetApiAdminOrdersResponses, GetApiAdminProductsData, GetApiAdminProductsOptionsData, GetApiAdminProductsOptionsResponses, GetApiAdminProductsResponses, GetApiOrderByIdData, GetApiOrderByIdErrors, GetApiOrderByIdResponses, GetApiOrderByNumberByOrderNumberData, GetApiOrderByNumberByOrderNumberErrors, GetApiOrderByNumberByOrderNumberResponses, GetApiProductsByIdData, GetApiProductsByIdErrors, GetApiProductsByIdResponses, GetApiProductsData, GetApiProductsResponses, GetApiProductsSuggestData, GetApiProductsSuggestResponses, GetProductByIdAdminData, GetProductByIdAdminErrors, GetProductByIdAdminResponses, GetUsersMeData, GetUsersMeResponses, PatchApiAdminOrdersByIdStatusData, PatchApiAdminOrdersByIdStatusErrors, PatchApiAdminOrdersByIdStatusResponses, PatchApiAdminProductsByIdActivateData, PatchApiAdminProductsByIdActivateResponses, PostApiAdminProductsData, PostApiAdminProductsResponses, PostApiOrderData, PostApiOrderErrors, PostApiOrderResponses, PostApiPaymentsCreateIntentData, PostApiPaymentsCreateIntentResponses, PostApiPaymentsWebhookData, PostApiPaymentsWebhookResponses, PostAuthLoginData, PostAuthLoginResponses, PostAuthLogoutData, PostAuthLogoutResponses, PostAuthRefreshData, PostAuthRefreshResponses, PostAuthRegisterData, PostAuthRegisterResponses, PutApiAdminProductsByIdData, PutApiAdminProductsByIdImageData, PutApiAdminProductsByIdImageResponses, PutApiAdminProductsByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getApiAdminOrders = <ThrowOnError extends boolean = false>(options?: Options<GetApiAdminOrdersData, ThrowOnError>) => (options?.client ?? client).get<GetApiAdminOrdersResponses, unknown, ThrowOnError>({ url: '/api/admin/orders', ...options });

export const getApiAdminOrdersById = <ThrowOnError extends boolean = false>(options: Options<GetApiAdminOrdersByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiAdminOrdersByIdResponses, GetApiAdminOrdersByIdErrors, ThrowOnError>({ url: '/api/admin/orders/{id}', ...options });

export const patchApiAdminOrdersByIdStatus = <ThrowOnError extends boolean = false>(options: Options<PatchApiAdminOrdersByIdStatusData, ThrowOnError>) => (options.client ?? client).patch<PatchApiAdminOrdersByIdStatusResponses, PatchApiAdminOrdersByIdStatusErrors, ThrowOnError>({
    url: '/api/admin/orders/{id}/status',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiAdminProducts = <ThrowOnError extends boolean = false>(options?: Options<GetApiAdminProductsData, ThrowOnError>) => (options?.client ?? client).get<GetApiAdminProductsResponses, unknown, ThrowOnError>({ url: '/api/admin/products', ...options });

export const postApiAdminProducts = <ThrowOnError extends boolean = false>(options: Options<PostApiAdminProductsData, ThrowOnError>) => (options.client ?? client).post<PostApiAdminProductsResponses, unknown, ThrowOnError>({
    url: '/api/admin/products',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getProductByIdAdmin = <ThrowOnError extends boolean = false>(options: Options<GetProductByIdAdminData, ThrowOnError>) => (options.client ?? client).get<GetProductByIdAdminResponses, GetProductByIdAdminErrors, ThrowOnError>({ url: '/api/admin/products/{id}', ...options });

export const putApiAdminProductsById = <ThrowOnError extends boolean = false>(options: Options<PutApiAdminProductsByIdData, ThrowOnError>) => (options.client ?? client).put<PutApiAdminProductsByIdResponses, unknown, ThrowOnError>({
    url: '/api/admin/products/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const putApiAdminProductsByIdImage = <ThrowOnError extends boolean = false>(options: Options<PutApiAdminProductsByIdImageData, ThrowOnError>) => (options.client ?? client).put<PutApiAdminProductsByIdImageResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    url: '/api/admin/products/{id}/image',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

export const patchApiAdminProductsByIdActivate = <ThrowOnError extends boolean = false>(options: Options<PatchApiAdminProductsByIdActivateData, ThrowOnError>) => (options.client ?? client).patch<PatchApiAdminProductsByIdActivateResponses, unknown, ThrowOnError>({
    url: '/api/admin/products/{id}/activate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiAdminProductsOptions = <ThrowOnError extends boolean = false>(options?: Options<GetApiAdminProductsOptionsData, ThrowOnError>) => (options?.client ?? client).get<GetApiAdminProductsOptionsResponses, unknown, ThrowOnError>({ url: '/api/admin/products/options', ...options });

export const postAuthRegister = <ThrowOnError extends boolean = false>(options: Options<PostAuthRegisterData, ThrowOnError>) => (options.client ?? client).post<PostAuthRegisterResponses, unknown, ThrowOnError>({
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginData, ThrowOnError>) => (options.client ?? client).post<PostAuthLoginResponses, unknown, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postAuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutData, ThrowOnError>) => (options?.client ?? client).post<PostAuthLogoutResponses, unknown, ThrowOnError>({ url: '/auth/logout', ...options });

export const postAuthRefresh = <ThrowOnError extends boolean = false>(options?: Options<PostAuthRefreshData, ThrowOnError>) => (options?.client ?? client).post<PostAuthRefreshResponses, unknown, ThrowOnError>({ url: '/auth/refresh', ...options });

export const postApiOrder = <ThrowOnError extends boolean = false>(options: Options<PostApiOrderData, ThrowOnError>) => (options.client ?? client).post<PostApiOrderResponses, PostApiOrderErrors, ThrowOnError>({
    url: '/api/Order',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiOrderById = <ThrowOnError extends boolean = false>(options: Options<GetApiOrderByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiOrderByIdResponses, GetApiOrderByIdErrors, ThrowOnError>({ url: '/api/Order/{id}', ...options });

export const getApiOrderByNumberByOrderNumber = <ThrowOnError extends boolean = false>(options: Options<GetApiOrderByNumberByOrderNumberData, ThrowOnError>) => (options.client ?? client).get<GetApiOrderByNumberByOrderNumberResponses, GetApiOrderByNumberByOrderNumberErrors, ThrowOnError>({ url: '/api/Order/by-number/{orderNumber}', ...options });

export const postApiPaymentsCreateIntent = <ThrowOnError extends boolean = false>(options: Options<PostApiPaymentsCreateIntentData, ThrowOnError>) => (options.client ?? client).post<PostApiPaymentsCreateIntentResponses, unknown, ThrowOnError>({
    url: '/api/payments/create-intent',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiPaymentsWebhook = <ThrowOnError extends boolean = false>(options?: Options<PostApiPaymentsWebhookData, ThrowOnError>) => (options?.client ?? client).post<PostApiPaymentsWebhookResponses, unknown, ThrowOnError>({ url: '/api/payments/webhook', ...options });

export const getApiProducts = <ThrowOnError extends boolean = false>(options?: Options<GetApiProductsData, ThrowOnError>) => (options?.client ?? client).get<GetApiProductsResponses, unknown, ThrowOnError>({ url: '/api/Products', ...options });

export const getApiProductsById = <ThrowOnError extends boolean = false>(options: Options<GetApiProductsByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiProductsByIdResponses, GetApiProductsByIdErrors, ThrowOnError>({ url: '/api/Products/{id}', ...options });

export const getApiProductsSuggest = <ThrowOnError extends boolean = false>(options?: Options<GetApiProductsSuggestData, ThrowOnError>) => (options?.client ?? client).get<GetApiProductsSuggestResponses, unknown, ThrowOnError>({ url: '/api/Products/suggest', ...options });

export const getUsersMe = <ThrowOnError extends boolean = false>(options?: Options<GetUsersMeData, ThrowOnError>) => (options?.client ?? client).get<GetUsersMeResponses, unknown, ThrowOnError>({ url: '/users/me', ...options });
