// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:7152/' | (string & {});
};

export type AdminCreateProductRequestDto = {
    name: string;
    description: string;
    palletType: string;
    condition: string;
    priceExVat: number | string;
    onHand: number | string;
    imgUrl: string;
    isActive: boolean;
};

export type AdminOrderDetailsDto = {
    id: number | string;
    orderNumber: string;
    createdAtUtc: string;
    customerFirstName: string;
    customerLastName: string;
    customerEmail: string;
    customerPhoneNumber: string;
    shippingStreet: string;
    shippingPostalCode: string;
    shippingCity: string;
    shippingCountry: string;
    orderStatus: OrderStatus;
    paymentStatus: PaymentStatus;
    paymentMethod: string;
    paymentIntentId: null | string;
    currency: string;
    productsSubtotal: number | string;
    shippingCost: number | string;
    taxTotal: number | string;
    grandTotal: number | string;
    items: Array<AdminOrderItemDto>;
};

export type AdminOrderItemDto = {
    productId: number | string;
    sku: string;
    productName: string;
    unitPrice: number | string;
    vatRate: number | string;
    quantity: number | string;
    lineTotal: number | string;
};

export type AdminOrderListItemDto = {
    id: number | string;
    orderNumber: string;
    createdAtUtc: string;
    customerName: string;
    customerEmail: string;
    orderStatus: OrderStatus;
    paymentStatus: PaymentStatus;
    grandTotal: number | string;
    paymentMethod: string;
};

export type AdminUpdateOrderStatusRequest = {
    orderStatus: OrderStatus;
};

export type AdminUpdateProductRequestDto = {
    id: number | string;
    name: string;
    description: string;
    palletType: string;
    condition: string;
    priceExVat: number | string;
    onHand: number | string;
    imgUrl: string;
    isActive: boolean;
};

export type CreateIntentRequest = {
    orderNumber: string;
    cartId: string;
};

export type CreateIntentResponse = {
    clientSecret: string;
};

export type CreateOrderItemRequestDto = {
    productId: number | string;
    quantity: number | string;
};

export type CreateOrderRequestDto = {
    customerFirstName: string;
    customerLastName: string;
    customerEmail: string;
    customerPhoneNumber: string;
    shippingAddress: ShippingAddressDto;
    items: Array<CreateOrderItemRequestDto>;
    currency?: string;
    shippingCost?: null | number | string;
};

export type LoginDto = {
    email: string;
    password: string;
};

export type OrderCreatedDto = {
    orderId: number | string;
    orderNumber: string;
    createdAtUtc: string;
    currency: string;
    productsSubtotal: number | string;
    shippingCost: number | string;
    taxTotal: number | string;
    grandTotal: number | string;
    orderStatus: OrderStatus;
    paymentStatus: PaymentStatus;
};

export type OrderStatus = number;

export type PagedResultOfAdminOrderDetailsDto = {
    page?: number | string;
    pageSize?: number | string;
    totalItems?: number | string;
    totalPages?: number | string;
    items?: Array<AdminOrderDetailsDto>;
};

export type PagedResultOfAdminOrderListItemDto = {
    page?: number | string;
    pageSize?: number | string;
    totalItems?: number | string;
    totalPages?: number | string;
    items?: Array<AdminOrderListItemDto>;
};

export type PagedResultOfProductDto = {
    page?: number | string;
    pageSize?: number | string;
    totalItems?: number | string;
    totalPages?: number | string;
    items?: Array<ProductDto>;
};

export type PaymentStatus = number;

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

export type ProductDto = {
    id: number | string;
    name: string;
    description: string;
    imgUrl: string;
    priceExVat: number | string;
    palletType: string;
    condition: string;
    stockStatus: string;
    onHand: number | string;
    reserved: number | string;
    available: number | string;
    isActive: boolean;
    sku: null | string;
    slug: null | string;
};

export type ProductSuggestionDto = {
    id: number | string;
    name: string;
    priceExVat: number | string;
    imgUrl: string;
    slug: null | string;
    sku: null | string;
};

export type RegisterDto = {
    email: string;
    password: string;
    displayName: string;
};

export type ShippingAddressDto = {
    street: string;
    city: string;
    postalCode: string;
    country: string;
};

export type ToggleActiveRequest = {
    isActive: boolean;
};

export type GetApiAdminOrdersData = {
    body?: never;
    path?: never;
    query?: {
        page?: number | string;
        pageSize?: number | string;
        query?: string;
        status?: string;
        from?: string;
        to?: string;
    };
    url: '/api/admin/orders';
};

export type GetApiAdminOrdersResponses = {
    /**
     * OK
     */
    200: PagedResultOfAdminOrderListItemDto;
};

export type GetApiAdminOrdersResponse = GetApiAdminOrdersResponses[keyof GetApiAdminOrdersResponses];

export type GetApiAdminOrdersByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/admin/orders/{id}';
};

export type GetApiAdminOrdersByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiAdminOrdersByIdError = GetApiAdminOrdersByIdErrors[keyof GetApiAdminOrdersByIdErrors];

export type GetApiAdminOrdersByIdResponses = {
    /**
     * OK
     */
    200: PagedResultOfAdminOrderDetailsDto;
};

export type GetApiAdminOrdersByIdResponse = GetApiAdminOrdersByIdResponses[keyof GetApiAdminOrdersByIdResponses];

export type PatchApiAdminOrdersByIdStatusData = {
    body: AdminUpdateOrderStatusRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/admin/orders/{id}/status';
};

export type PatchApiAdminOrdersByIdStatusErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PatchApiAdminOrdersByIdStatusError = PatchApiAdminOrdersByIdStatusErrors[keyof PatchApiAdminOrdersByIdStatusErrors];

export type PatchApiAdminOrdersByIdStatusResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PatchApiAdminOrdersByIdStatusResponse = PatchApiAdminOrdersByIdStatusResponses[keyof PatchApiAdminOrdersByIdStatusResponses];

export type GetApiAdminProductsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number | string;
        pageSize?: number | string;
        query?: string;
        sort?: string;
        type?: Array<string>;
        condition?: Array<string>;
        minPrice?: number | string;
        maxPrice?: number | string;
        isActive?: boolean;
    };
    url: '/api/admin/products';
};

export type GetApiAdminProductsResponses = {
    /**
     * OK
     */
    200: PagedResultOfProductDto;
};

export type GetApiAdminProductsResponse = GetApiAdminProductsResponses[keyof GetApiAdminProductsResponses];

export type PostApiAdminProductsData = {
    body: AdminCreateProductRequestDto;
    path?: never;
    query?: never;
    url: '/api/admin/products';
};

export type PostApiAdminProductsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetProductByIdAdminData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/admin/products/{id}';
};

export type GetProductByIdAdminErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetProductByIdAdminError = GetProductByIdAdminErrors[keyof GetProductByIdAdminErrors];

export type GetProductByIdAdminResponses = {
    /**
     * OK
     */
    200: ProductDto;
};

export type GetProductByIdAdminResponse = GetProductByIdAdminResponses[keyof GetProductByIdAdminResponses];

export type PutApiAdminProductsByIdData = {
    body: AdminUpdateProductRequestDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/admin/products/{id}';
};

export type PutApiAdminProductsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiAdminProductsByIdImageData = {
    body: {
        ContentType?: string;
        ContentDisposition?: string;
        Headers?: {
            [key: string]: Array<string>;
        };
        Length?: number | string;
        Name?: string;
        FileName?: string;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/api/admin/products/{id}/image';
};

export type PutApiAdminProductsByIdImageResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatchApiAdminProductsByIdActivateData = {
    body?: null | ToggleActiveRequest;
    path: {
        id: number;
    };
    query?: {
        isActive?: boolean;
    };
    url: '/api/admin/products/{id}/activate';
};

export type PatchApiAdminProductsByIdActivateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminProductsOptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/products/options';
};

export type GetApiAdminProductsOptionsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAuthRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAuthLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAuthRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiOrderData = {
    body: CreateOrderRequestDto;
    path?: never;
    query?: never;
    url: '/api/Order';
};

export type PostApiOrderErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostApiOrderError = PostApiOrderErrors[keyof PostApiOrderErrors];

export type PostApiOrderResponses = {
    /**
     * Created
     */
    201: OrderCreatedDto;
};

export type PostApiOrderResponse = PostApiOrderResponses[keyof PostApiOrderResponses];

export type GetApiOrderByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Order/{id}';
};

export type GetApiOrderByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiOrderByIdError = GetApiOrderByIdErrors[keyof GetApiOrderByIdErrors];

export type GetApiOrderByIdResponses = {
    /**
     * OK
     */
    200: OrderCreatedDto;
};

export type GetApiOrderByIdResponse = GetApiOrderByIdResponses[keyof GetApiOrderByIdResponses];

export type GetApiOrderByNumberByOrderNumberData = {
    body?: never;
    path: {
        orderNumber: string;
    };
    query?: never;
    url: '/api/Order/by-number/{orderNumber}';
};

export type GetApiOrderByNumberByOrderNumberErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiOrderByNumberByOrderNumberError = GetApiOrderByNumberByOrderNumberErrors[keyof GetApiOrderByNumberByOrderNumberErrors];

export type GetApiOrderByNumberByOrderNumberResponses = {
    /**
     * OK
     */
    200: OrderCreatedDto;
};

export type GetApiOrderByNumberByOrderNumberResponse = GetApiOrderByNumberByOrderNumberResponses[keyof GetApiOrderByNumberByOrderNumberResponses];

export type PostApiPaymentsCreateIntentData = {
    body: CreateIntentRequest;
    path?: never;
    query?: never;
    url: '/api/payments/create-intent';
};

export type PostApiPaymentsCreateIntentResponses = {
    /**
     * OK
     */
    200: CreateIntentResponse;
};

export type PostApiPaymentsCreateIntentResponse = PostApiPaymentsCreateIntentResponses[keyof PostApiPaymentsCreateIntentResponses];

export type PostApiPaymentsWebhookData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/payments/webhook';
};

export type PostApiPaymentsWebhookResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiProductsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number | string;
        pageSize?: number | string;
        query?: string;
        sort?: string;
        type?: Array<string>;
        condition?: Array<string>;
        minPrice?: number | string;
        maxPrice?: number | string;
    };
    url: '/api/Products';
};

export type GetApiProductsResponses = {
    /**
     * OK
     */
    200: PagedResultOfProductDto;
};

export type GetApiProductsResponse = GetApiProductsResponses[keyof GetApiProductsResponses];

export type GetApiProductsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Products/{id}';
};

export type GetApiProductsByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiProductsByIdError = GetApiProductsByIdErrors[keyof GetApiProductsByIdErrors];

export type GetApiProductsByIdResponses = {
    /**
     * OK
     */
    200: ProductDto;
};

export type GetApiProductsByIdResponse = GetApiProductsByIdResponses[keyof GetApiProductsByIdResponses];

export type GetApiProductsSuggestData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        take?: number | string;
    };
    url: '/api/Products/suggest';
};

export type GetApiProductsSuggestResponses = {
    /**
     * OK
     */
    200: Array<ProductSuggestionDto>;
};

export type GetApiProductsSuggestResponse = GetApiProductsSuggestResponses[keyof GetApiProductsSuggestResponses];

export type GetUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetUsersMeResponses = {
    /**
     * OK
     */
    200: unknown;
};
