// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:7152/' | (string & {});
};

export type AdminCreateProductRequestDto = {
    name: string;
    description: string;
    palletType: string;
    condition: string;
    priceExVat: number | string;
    vatRatePercent: number | string;
    onHand: number | string;
    images: Array<AdminProductImageRequestDto>;
    isActive: boolean;
};

export type AdminOrderDetailsDto = {
    id: number | string;
    orderNumber: string;
    createdAtUtc: string;
    customerFirstName: string;
    customerLastName: string;
    customerEmail: string;
    customerPhoneNumber: string;
    shippingStreet: string;
    shippingPostalCode: string;
    shippingCity: string;
    shippingCountry: string;
    orderStatus: OrderStatus;
    paymentStatus: PaymentStatus;
    paymentMethod: string;
    paymentIntentId: null | string;
    currency: string;
    productsSubtotal: number | string;
    shippingCost: number | string;
    vatTotal: number | string;
    grandTotal: number | string;
    trackingNumber: null | string;
    trackingUrl: null | string;
    items: Array<AdminOrderItemDto>;
};

export type AdminOrderItemDto = {
    productId: number | string;
    sku: string;
    productName: string;
    unitPriceExVat: number | string;
    vatRatePercent: number | string;
    unitVatAmount: number | string;
    unitPriceIncVat: number | string;
    quantity: number | string;
    lineTotalExVat: number | string;
    lineTotalVat: number | string;
    lineTotalIncVat: number | string;
};

export type AdminOrderListItemDto = {
    id: number | string;
    orderNumber: string;
    createdAtUtc: string;
    customerName: string;
    customerEmail: string;
    orderStatus: OrderStatus;
    paymentStatus: PaymentStatus;
    grandTotal: number | string;
    paymentMethod: string;
};

export type AdminProductImageRequestDto = {
    url: string;
    sortOrder: number | string;
    isPrimary: boolean;
    altText: null | string;
};

export type AdminProductOptionsDto = {
    productTypes: Array<EnumOptionDto>;
    productConditions: Array<EnumOptionDto>;
    vatRates: Array<EnumOptionDto>;
};

export type AdminSetTrackingRequest = {
    trackingNumber: string;
    markAsShipped?: boolean;
};

export type AdminUpdateOrderStatusRequest = {
    orderStatus: OrderStatus;
};

export type AdminUpdateProductRequestDto = {
    id: number | string;
    name: string;
    description: string;
    palletType: string;
    condition: string;
    priceExVat: number | string;
    vatRatePercent: number | string;
    onHand: number | string;
    images: Array<AdminProductImageRequestDto>;
    isActive: boolean;
};

export type AuthSessionResponseDto = {
    expiresAt: string;
};

export type BlobUploadRequestResponse = {
    uploadUrl: string;
    publicUrl: string;
};

export type ConfirmEmailDto = {
    userId: number | string;
    token: string;
};

export type CreateIntentRequest = {
    orderNumber: string;
    cartId: string;
};

export type CreateIntentResponse = {
    clientSecret: string;
};

export type CreateOrderItemRequestDto = {
    productId: number | string;
    quantity: number | string;
};

export type CreateOrderRequestDto = {
    items: Array<CreateOrderItemRequestDto>;
    cartId: string;
    currency?: string;
    reservationTtlMinutes?: number | string;
};

export type EnumOptionDto = {
    value: string;
    label: string;
    intValue: number | string;
};

export type ForgotPasswordDto = {
    email: string;
};

export type LoginDto = {
    email: string;
    password: string;
};

export type MeDto = {
    userId: number | string;
    email: string;
    displayName: null | string;
    profile: UserProfileDto;
    roles: Array<string>;
};

export type MyOrderListItemDto = {
    createdAtUtc: string;
    orderNumber: string;
    orderStatus: OrderStatus;
    grandTotal: number | string;
    trackingUrl: null | string;
    receiptUrl: null | string;
};

export type OrderCreatedDto = {
    orderId: number | string;
    orderNumber: string;
    createdAtUtc: string;
    currency: string;
    productsSubtotal: number | string;
    shippingCost: number | string;
    vatTotal: number | string;
    grandTotal: number | string;
    orderStatus: OrderStatus;
    paymentStatus: PaymentStatus;
    customerFirstName: null | string;
    customerLastName: null | string;
    customerEmail: null | string;
    customerPhoneNumber: null | string;
    shippingAddress: null | ShippingAddressDto;
    shippingCarrier: ShippingCarrier;
    shippingMethod: ShippingMethod;
    servicePointId: null | string;
    userId: null | number | string;
};

export type OrderDetailsDto = {
    orderId: number | string;
    orderNumber: string;
    createdAtUtc: string;
    currency: string;
    productsSubtotal: number | string;
    shippingCost: number | string;
    vatTotal: number | string;
    grandTotal: number | string;
    orderStatus: OrderStatus;
    paymentStatus: PaymentStatus;
    customerFirstName: null | string;
    customerLastName: null | string;
    customerEmail: null | string;
    customerPhoneNumber: null | string;
    shippingAddress: null | ShippingAddressDto;
    shippingCarrier: ShippingCarrier;
    shippingMethod: ShippingMethod;
    servicePointId: null | string;
    trackingNumber: null | string;
    trackingUrl: null | string;
    items: Array<OrderItemDto>;
    userId: null | number | string;
};

export type OrderItemDto = {
    productId: number | string;
    productName: string;
    quantity: number | string;
    unitPriceExVat: number | string;
    lineTotalExVat: number | string;
};

export const OrderStatus = {
    PENDING: 'Pending',
    CONFIRMED: 'Confirmed',
    PROCESSING: 'Processing',
    SHIPPED: 'Shipped',
    COMPLETED: 'Completed',
    CANCELLED: 'Cancelled',
    FAILED: 'Failed',
    REFUNDED: 'Refunded'
} as const;

export type OrderStatus = typeof OrderStatus[keyof typeof OrderStatus];

export type PagedResultOfAdminOrderListItemDto = {
    page?: number | string;
    pageSize?: number | string;
    totalItems?: number | string;
    totalPages?: number | string;
    items?: Array<AdminOrderListItemDto>;
};

export type PagedResultOfProductDto = {
    page?: number | string;
    pageSize?: number | string;
    totalItems?: number | string;
    totalPages?: number | string;
    items?: Array<ProductDto>;
};

export const PaymentStatus = {
    NONE: 'None',
    REQUIRES_PAYMENT: 'RequiresPayment',
    AUTHORIZED: 'Authorized',
    CAPTURED: 'Captured',
    FAILED: 'Failed',
    CANCELLED: 'Cancelled',
    REFUNDED: 'Refunded'
} as const;

export type PaymentStatus = typeof PaymentStatus[keyof typeof PaymentStatus];

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

export type ProductDto = {
    id: number | string;
    name: string;
    description: string;
    primaryImgUrl: null | string;
    images: Array<ProductImageDto>;
    priceExVat: number | string;
    vatRatePercent: number | string;
    palletType: string;
    condition: string;
    stockStatus: string;
    onHand: number | string;
    reserved: number | string;
    available: number | string;
    isActive: boolean;
    sku: null | string;
    slug: null | string;
};

export type ProductImageDto = {
    id: number | string;
    url: string;
    sortOrder: number | string;
    isPrimary: boolean;
    altText: null | string;
};

export type ProductSuggestionDto = {
    id: number | string;
    name: string;
    priceExVat: number | string;
    imgUrl: null | string;
    slug: null | string;
    sku: null | string;
};

export type RegisterDto = {
    email: string;
    displayName: string;
    password: string;
};

export type RequestUploadDto = {
    fileName: string;
    contentType: string;
};

export type ResendVerificationDto = {
    email: string;
};

export type ResetPasswordDto = {
    email: string;
    token: string;
    newPassword: string;
};

export type ServicePointDto = {
    id: string;
    name: string;
    street: string;
    postalCode: string;
    city: string;
};

export type SetCartReservationDto = {
    cartId: string;
    productId: number | string;
    quantity: number | string;
    reservationTtlMinutes?: number | string;
};

export type SetDefaultAddressDto = {
    defaultShippingAddressId: null | number | string;
};

export type SetShippingSelectionDto = {
    carrier: string;
    method: string;
    shippingCost: number | string;
    servicePointId: null | string;
};

export type ShippingAddressDto = {
    street: string;
    city: string;
    postalCode: string;
    country: string;
};

export const ShippingCarrier = { NONE: 'None', POST_NORD: 'PostNord' } as const;

export type ShippingCarrier = typeof ShippingCarrier[keyof typeof ShippingCarrier];

export const ShippingMethod = {
    NONE: 'None',
    SERVICE_POINT: 'ServicePoint',
    HOME_DELIVERY: 'HomeDelivery'
} as const;

export type ShippingMethod = typeof ShippingMethod[keyof typeof ShippingMethod];

export type ToggleActiveRequest = {
    isActive: boolean;
};

export type UpdateOrderCustomerDto = {
    firstName: string;
    lastName: string;
    email: string;
    phone: null | string;
};

export type UpdateOrderShippingAddressDto = {
    street: string;
    city: string;
    postalCode: string;
    country?: string;
};

export type UpdateProfileDto = {
    firstName: string;
    lastName: string;
    phone: null | string;
    defaultShippingAddressId: null | number | string;
};

export type UpsertAddressDto = {
    label: null | string;
    street: string;
    city: string;
    postalCode: string;
    country: null | string;
};

export type UserAddressDto = {
    id: number | string;
    label: string;
    street: string;
    city: string;
    postalCode: string;
    country: string;
};

export type UserProfileDto = {
    firstName: string;
    lastName: string;
    phone: string;
    defaultShippingAddressId: null | number | string;
    addresses: Array<UserAddressDto>;
};

export type GetApiAdminOrdersData = {
    body?: never;
    path?: never;
    query?: {
        page?: number | string;
        pageSize?: number | string;
        query?: string;
        status?: string;
        from?: string;
        to?: string;
    };
    url: '/api/admin/orders';
};

export type GetApiAdminOrdersResponses = {
    /**
     * OK
     */
    200: PagedResultOfAdminOrderListItemDto;
};

export type GetApiAdminOrdersResponse = GetApiAdminOrdersResponses[keyof GetApiAdminOrdersResponses];

export type GetApiAdminOrdersByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/admin/orders/{id}';
};

export type GetApiAdminOrdersByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiAdminOrdersByIdError = GetApiAdminOrdersByIdErrors[keyof GetApiAdminOrdersByIdErrors];

export type GetApiAdminOrdersByIdResponses = {
    /**
     * OK
     */
    200: AdminOrderDetailsDto;
};

export type GetApiAdminOrdersByIdResponse = GetApiAdminOrdersByIdResponses[keyof GetApiAdminOrdersByIdResponses];

export type PatchApiAdminOrdersByIdStatusData = {
    body: AdminUpdateOrderStatusRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/admin/orders/{id}/status';
};

export type PatchApiAdminOrdersByIdStatusErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PatchApiAdminOrdersByIdStatusError = PatchApiAdminOrdersByIdStatusErrors[keyof PatchApiAdminOrdersByIdStatusErrors];

export type PatchApiAdminOrdersByIdStatusResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PatchApiAdminOrdersByIdStatusResponse = PatchApiAdminOrdersByIdStatusResponses[keyof PatchApiAdminOrdersByIdStatusResponses];

export type PatchApiAdminOrdersByIdTrackingData = {
    body: AdminSetTrackingRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/admin/orders/{id}/tracking';
};

export type PatchApiAdminOrdersByIdTrackingErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PatchApiAdminOrdersByIdTrackingError = PatchApiAdminOrdersByIdTrackingErrors[keyof PatchApiAdminOrdersByIdTrackingErrors];

export type PatchApiAdminOrdersByIdTrackingResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PatchApiAdminOrdersByIdTrackingResponse = PatchApiAdminOrdersByIdTrackingResponses[keyof PatchApiAdminOrdersByIdTrackingResponses];

export type GetApiAdminProductsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number | string;
        pageSize?: number | string;
        query?: string;
        sort?: string;
        type?: Array<string>;
        condition?: Array<string>;
        minPrice?: number | string;
        maxPrice?: number | string;
        isActive?: boolean;
    };
    url: '/api/admin/products';
};

export type GetApiAdminProductsResponses = {
    /**
     * OK
     */
    200: PagedResultOfProductDto;
};

export type GetApiAdminProductsResponse = GetApiAdminProductsResponses[keyof GetApiAdminProductsResponses];

export type PostApiAdminProductsData = {
    body: AdminCreateProductRequestDto;
    path?: never;
    query?: never;
    url: '/api/admin/products';
};

export type PostApiAdminProductsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostApiAdminProductsError = PostApiAdminProductsErrors[keyof PostApiAdminProductsErrors];

export type PostApiAdminProductsResponses = {
    /**
     * Created
     */
    201: ProductDto;
};

export type PostApiAdminProductsResponse = PostApiAdminProductsResponses[keyof PostApiAdminProductsResponses];

export type GetProductByIdAdminData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/admin/products/{id}';
};

export type GetProductByIdAdminErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetProductByIdAdminError = GetProductByIdAdminErrors[keyof GetProductByIdAdminErrors];

export type GetProductByIdAdminResponses = {
    /**
     * OK
     */
    200: ProductDto;
};

export type GetProductByIdAdminResponse = GetProductByIdAdminResponses[keyof GetProductByIdAdminResponses];

export type PutApiAdminProductsByIdData = {
    body: AdminUpdateProductRequestDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/admin/products/{id}';
};

export type PutApiAdminProductsByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutApiAdminProductsByIdError = PutApiAdminProductsByIdErrors[keyof PutApiAdminProductsByIdErrors];

export type PutApiAdminProductsByIdResponses = {
    /**
     * OK
     */
    200: ProductDto;
};

export type PutApiAdminProductsByIdResponse = PutApiAdminProductsByIdResponses[keyof PutApiAdminProductsByIdResponses];

export type PatchApiAdminProductsByIdActivateData = {
    body?: null | ToggleActiveRequest;
    path: {
        id: number;
    };
    query?: {
        isActive?: boolean;
    };
    url: '/api/admin/products/{id}/activate';
};

export type PatchApiAdminProductsByIdActivateErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PatchApiAdminProductsByIdActivateError = PatchApiAdminProductsByIdActivateErrors[keyof PatchApiAdminProductsByIdActivateErrors];

export type PatchApiAdminProductsByIdActivateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PatchApiAdminProductsByIdActivateResponse = PatchApiAdminProductsByIdActivateResponses[keyof PatchApiAdminProductsByIdActivateResponses];

export type GetApiAdminProductsOptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/products/options';
};

export type GetApiAdminProductsOptionsResponses = {
    /**
     * OK
     */
    200: AdminProductOptionsDto;
};

export type GetApiAdminProductsOptionsResponse = GetApiAdminProductsOptionsResponses[keyof GetApiAdminProductsOptionsResponses];

export type PostAuthRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAuthLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * OK
     */
    200: AuthSessionResponseDto;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAuthRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type PostAuthRefreshError = PostAuthRefreshErrors[keyof PostAuthRefreshErrors];

export type PostAuthRefreshResponses = {
    /**
     * OK
     */
    200: AuthSessionResponseDto;
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type PostAuthForgotPasswordData = {
    body: ForgotPasswordDto;
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type PostAuthForgotPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAuthResetPasswordData = {
    body: ResetPasswordDto;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type PostAuthResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAuthResendVerificationData = {
    body: ResendVerificationDto;
    path?: never;
    query?: never;
    url: '/auth/resend-verification';
};

export type PostAuthResendVerificationResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAuthConfirmEmailData = {
    body: ConfirmEmailDto;
    path?: never;
    query?: never;
    url: '/auth/confirm-email';
};

export type PostAuthConfirmEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiBlobUploadRequestData = {
    body: RequestUploadDto;
    path?: never;
    query?: never;
    url: '/api/BlobUpload/request';
};

export type PostApiBlobUploadRequestErrors = {
    /**
     * Bad Request
     */
    400: string;
};

export type PostApiBlobUploadRequestError = PostApiBlobUploadRequestErrors[keyof PostApiBlobUploadRequestErrors];

export type PostApiBlobUploadRequestResponses = {
    /**
     * OK
     */
    200: BlobUploadRequestResponse;
};

export type PostApiBlobUploadRequestResponse = PostApiBlobUploadRequestResponses[keyof PostApiBlobUploadRequestResponses];

export type GetApiMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type GetApiMeErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type GetApiMeError = GetApiMeErrors[keyof GetApiMeErrors];

export type GetApiMeResponses = {
    /**
     * OK
     */
    200: MeDto;
};

export type GetApiMeResponse = GetApiMeResponses[keyof GetApiMeResponses];

export type PutApiMeProfileData = {
    body: UpdateProfileDto;
    path?: never;
    query?: never;
    url: '/api/me/profile';
};

export type PutApiMeProfileErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type PutApiMeProfileError = PutApiMeProfileErrors[keyof PutApiMeProfileErrors];

export type PutApiMeProfileResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiMeProfileResponse = PutApiMeProfileResponses[keyof PutApiMeProfileResponses];

export type PostApiMeAddressesData = {
    body: UpsertAddressDto;
    path?: never;
    query?: never;
    url: '/api/me/addresses';
};

export type PostApiMeAddressesErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type PostApiMeAddressesError = PostApiMeAddressesErrors[keyof PostApiMeAddressesErrors];

export type PostApiMeAddressesResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type PatchApiMeProfileDefaultAddressData = {
    body: SetDefaultAddressDto;
    path?: never;
    query?: never;
    url: '/api/me/profile/default-address';
};

export type PatchApiMeProfileDefaultAddressErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type PatchApiMeProfileDefaultAddressError = PatchApiMeProfileDefaultAddressErrors[keyof PatchApiMeProfileDefaultAddressErrors];

export type PatchApiMeProfileDefaultAddressResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PatchApiMeProfileDefaultAddressResponse = PatchApiMeProfileDefaultAddressResponses[keyof PatchApiMeProfileDefaultAddressResponses];

export type GetApiMeOrdersData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number | string;
        take?: number | string;
    };
    url: '/api/me/orders';
};

export type GetApiMeOrdersResponses = {
    /**
     * OK
     */
    200: Array<MyOrderListItemDto>;
};

export type GetApiMeOrdersResponse = GetApiMeOrdersResponses[keyof GetApiMeOrdersResponses];

export type GetApiMeOrdersByOrderNumberData = {
    body?: never;
    path: {
        orderNumber: string;
    };
    query?: never;
    url: '/api/me/orders/{orderNumber}';
};

export type GetApiMeOrdersByOrderNumberErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiMeOrdersByOrderNumberError = GetApiMeOrdersByOrderNumberErrors[keyof GetApiMeOrdersByOrderNumberErrors];

export type GetApiMeOrdersByOrderNumberResponses = {
    /**
     * OK
     */
    200: OrderDetailsDto;
};

export type GetApiMeOrdersByOrderNumberResponse = GetApiMeOrdersByOrderNumberResponses[keyof GetApiMeOrdersByOrderNumberResponses];

export type PostApiOrderData = {
    body: CreateOrderRequestDto;
    path?: never;
    query?: never;
    url: '/api/Order';
};

export type PostApiOrderErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostApiOrderError = PostApiOrderErrors[keyof PostApiOrderErrors];

export type PostApiOrderResponses = {
    /**
     * Created
     */
    201: OrderCreatedDto;
};

export type PostApiOrderResponse = PostApiOrderResponses[keyof PostApiOrderResponses];

export type GetApiOrderByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Order/{id}';
};

export type GetApiOrderByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiOrderByIdError = GetApiOrderByIdErrors[keyof GetApiOrderByIdErrors];

export type GetApiOrderByIdResponses = {
    /**
     * OK
     */
    200: OrderDetailsDto;
};

export type GetApiOrderByIdResponse = GetApiOrderByIdResponses[keyof GetApiOrderByIdResponses];

export type GetApiOrderByNumberByOrderNumberData = {
    body?: never;
    path: {
        orderNumber: string;
    };
    query?: never;
    url: '/api/Order/by-number/{orderNumber}';
};

export type GetApiOrderByNumberByOrderNumberErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiOrderByNumberByOrderNumberError = GetApiOrderByNumberByOrderNumberErrors[keyof GetApiOrderByNumberByOrderNumberErrors];

export type GetApiOrderByNumberByOrderNumberResponses = {
    /**
     * OK
     */
    200: OrderDetailsDto;
};

export type GetApiOrderByNumberByOrderNumberResponse = GetApiOrderByNumberByOrderNumberResponses[keyof GetApiOrderByNumberByOrderNumberResponses];

export type PatchApiOrderByNumberByOrderNumberCustomerData = {
    body: UpdateOrderCustomerDto;
    path: {
        orderNumber: string;
    };
    query?: never;
    url: '/api/Order/by-number/{orderNumber}/customer';
};

export type PatchApiOrderByNumberByOrderNumberCustomerErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PatchApiOrderByNumberByOrderNumberCustomerError = PatchApiOrderByNumberByOrderNumberCustomerErrors[keyof PatchApiOrderByNumberByOrderNumberCustomerErrors];

export type PatchApiOrderByNumberByOrderNumberCustomerResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PatchApiOrderByNumberByOrderNumberCustomerResponse = PatchApiOrderByNumberByOrderNumberCustomerResponses[keyof PatchApiOrderByNumberByOrderNumberCustomerResponses];

export type PatchApiOrderByNumberByOrderNumberShippingAddressData = {
    body: UpdateOrderShippingAddressDto;
    path: {
        orderNumber: string;
    };
    query?: never;
    url: '/api/Order/by-number/{orderNumber}/shipping-address';
};

export type PatchApiOrderByNumberByOrderNumberShippingAddressErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PatchApiOrderByNumberByOrderNumberShippingAddressError = PatchApiOrderByNumberByOrderNumberShippingAddressErrors[keyof PatchApiOrderByNumberByOrderNumberShippingAddressErrors];

export type PatchApiOrderByNumberByOrderNumberShippingAddressResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PatchApiOrderByNumberByOrderNumberShippingAddressResponse = PatchApiOrderByNumberByOrderNumberShippingAddressResponses[keyof PatchApiOrderByNumberByOrderNumberShippingAddressResponses];

export type PostApiPaymentsCreateIntentData = {
    body: CreateIntentRequest;
    path?: never;
    query?: never;
    url: '/api/payments/create-intent';
};

export type PostApiPaymentsCreateIntentResponses = {
    /**
     * OK
     */
    200: CreateIntentResponse;
};

export type PostApiPaymentsCreateIntentResponse = PostApiPaymentsCreateIntentResponses[keyof PostApiPaymentsCreateIntentResponses];

export type PostApiPaymentsWebhookData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/payments/webhook';
};

export type PostApiPaymentsWebhookResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiProductsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number | string;
        pageSize?: number | string;
        query?: string;
        sort?: string;
        type?: Array<string>;
        condition?: Array<string>;
        minPrice?: number | string;
        maxPrice?: number | string;
        inStock?: boolean;
    };
    url: '/api/Products';
};

export type GetApiProductsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type GetApiProductsError = GetApiProductsErrors[keyof GetApiProductsErrors];

export type GetApiProductsResponses = {
    /**
     * OK
     */
    200: PagedResultOfProductDto;
};

export type GetApiProductsResponse = GetApiProductsResponses[keyof GetApiProductsResponses];

export type GetApiProductsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Products/{id}';
};

export type GetApiProductsByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiProductsByIdError = GetApiProductsByIdErrors[keyof GetApiProductsByIdErrors];

export type GetApiProductsByIdResponses = {
    /**
     * OK
     */
    200: ProductDto;
};

export type GetApiProductsByIdResponse = GetApiProductsByIdResponses[keyof GetApiProductsByIdResponses];

export type GetApiProductsSuggestData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        take?: number | string;
    };
    url: '/api/Products/suggest';
};

export type GetApiProductsSuggestResponses = {
    /**
     * OK
     */
    200: Array<ProductSuggestionDto>;
};

export type GetApiProductsSuggestResponse = GetApiProductsSuggestResponses[keyof GetApiProductsSuggestResponses];

export type PutApiCartReservationsData = {
    body: SetCartReservationDto;
    path?: never;
    query?: never;
    url: '/api/cart/reservations';
};

export type PutApiCartReservationsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PutApiCartReservationsError = PutApiCartReservationsErrors[keyof PutApiCartReservationsErrors];

export type PutApiCartReservationsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiShippingServicePointsData = {
    body?: never;
    path?: never;
    query?: {
        postalCode?: string;
        city?: string;
    };
    url: '/api/Shipping/service-points';
};

export type GetApiShippingServicePointsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type GetApiShippingServicePointsError = GetApiShippingServicePointsErrors[keyof GetApiShippingServicePointsErrors];

export type GetApiShippingServicePointsResponses = {
    /**
     * OK
     */
    200: Array<ServicePointDto>;
};

export type GetApiShippingServicePointsResponse = GetApiShippingServicePointsResponses[keyof GetApiShippingServicePointsResponses];

export type PutApiShippingOrdersByOrderNumberSelectionData = {
    body: SetShippingSelectionDto;
    path: {
        orderNumber: string;
    };
    query?: never;
    url: '/api/Shipping/orders/{orderNumber}/selection';
};

export type PutApiShippingOrdersByOrderNumberSelectionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutApiShippingOrdersByOrderNumberSelectionError = PutApiShippingOrdersByOrderNumberSelectionErrors[keyof PutApiShippingOrdersByOrderNumberSelectionErrors];

export type PutApiShippingOrdersByOrderNumberSelectionResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiShippingOrdersByOrderNumberSelectionResponse = PutApiShippingOrdersByOrderNumberSelectionResponses[keyof PutApiShippingOrdersByOrderNumberSelectionResponses];
